/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;
import Utils.IDExporter;
import Utils.JdbcConnection;
import Utils.Scrap;
import com.jml.gorigrama.GorigramaEntity;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import javax.swing.text.Document;
import Utils.Pair;
import java.awt.Image;

/**
 *
 * @author jmlucero
 */
public class Definitions extends javax.swing.JFrame {

    /**
     * Creates new form Definiciones
     */
    Document doc;
    GorigramaEntity crucigrama;
    boolean saveAllSQL = false;
    boolean editing = false;
    Executor resetStatusText = CompletableFuture.delayedExecutor(3, TimeUnit.SECONDS);

    public Definitions() {
         initComponents();
            Image image = Toolkit.getDefaultToolkit().getImage("src/main/resources/imgs/icon_small.png");
            ImageIcon icon = new ImageIcon(image);
            setIconImage(image);

       
    }

    private void scheduleResetStatus() {
        resetStatusText.execute(() -> statusJLabel.setText("STATUS"));
    }

    public Definitions(GorigramaEntity crucigrama) {
        this();
        this.crucigrama = crucigrama;
        listarDefs();
    }

    private void cargarHorizontales(List<Pair<Integer, String>> listaH) {
        System.out.println("Cantidad de Defs Horizontales: " + listaH.size());
        String[] strings = new String[listaH.size()];
        for (int i = 0; i < strings.length; i++) {
            strings[i] = listaH.get(i).first + ". " + listaH.get(i).second;
        }
        horizontItemList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void cargarVerticales(List<Pair<Integer, String>> listaV) {
        System.out.println("Cantidad de Defs Verticales: " + listaV.size());
        String[] strings = new String[listaV.size()];
        for (int i = 0; i < strings.length; i++) {
            strings[i] = listaV.get(i).first + ". " + listaV.get(i).second;
        }
        verticalItemList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return strings.length;
            }
            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        verticalItemList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        horizontItemList1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        definitionTextPane = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        updateDB = new javax.swing.JButton();
        cargarDefBtn = new javax.swing.JButton();
        palabraSeleccionada = new javax.swing.JLabel();
        cargadDefsFromDB = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        saveToIDButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        saveAllCheckBox = new javax.swing.JCheckBox();
        editModeToggle = new javax.swing.JToggleButton();
        statusJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Words Definitions");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HORIZONTALES");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VERTICALES");

        verticalItemList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        verticalItemList.setValueIsAdjusting(true);
        verticalItemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                verticalItemListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(verticalItemList);

        horizontItemList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        horizontItemList1.setMaximumSize(new java.awt.Dimension(100, 90));
        horizontItemList1.setValueIsAdjusting(true);
        horizontItemList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemClicked(evt);
            }
        });
        horizontItemList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                horizontItemList1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(horizontItemList1);

        definitionTextPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(definitionTextPane);

        jButton2.setMnemonic('S');
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarDef(evt);
            }
        });

        updateDB.setText("UPDATE DB");
        updateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDB(evt);
            }
        });

        cargarDefBtn.setText("Cargar Defs (Scrap)");
        cargarDefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDefiniciones(evt);
            }
        });

        palabraSeleccionada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        palabraSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabraSeleccionada.setText("Palabra seleccionada...");
        palabraSeleccionada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        cargadDefsFromDB.setText("Cargar Definiciones from DB");
        cargadDefsFromDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargadDefsFromDBActionPerformed(evt);
            }
        });

        jButton4.setText("Scrap word");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrapWord(evt);
            }
        });

        saveToIDButton.setText("SAVE TO INDESIGN");
        saveToIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToIDButtonActionPerformed(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 51));

        saveAllCheckBox.setText("Save All");
        saveAllCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saveAllCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        saveAllCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                saveAllCheckBoxItemStateChanged(evt);
            }
        });

        editModeToggle.setText("EDIT MODE");
        editModeToggle.setToolTipText("Lock load methods...");
        editModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editModeToggleActionPerformed(evt);
            }
        });

        statusJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusJLabel.setText("STATUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(269, 269, 269)
                                .addComponent(jButton2))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveToIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateDB)
                                .addGap(36, 36, 36)
                                .addComponent(saveAllCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editModeToggle)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(palabraSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cargarDefBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cargadDefsFromDB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarDefBtn)
                    .addComponent(cargadDefsFromDB)
                    .addComponent(editModeToggle))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(palabraSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(statusJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(updateDB)
                    .addComponent(jButton4)
                    .addComponent(saveAllCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveToIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemClicked

    }//GEN-LAST:event_ItemClicked
    private void listarDefs() {
        List<String> words = new ArrayList();
        crucigrama.getHorizPairsList().forEach(t -> words.add(t.second));
        crucigrama.getVertiPairList().forEach(t -> words.add(t.second));
        words.sort((String o1, String o2) -> o1.compareTo(o2));
        words.forEach(System.out::println);
        cargarHorizontales(crucigrama.getHorizPairsList());
        cargarVerticales(crucigrama.getVertiPairList());
    }

    private void cargarDefs() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SwingWorker sw = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                int progress = 0;
                int cant = crucigrama.getDefiniciones().size();
                for (Map.Entry<String, String> entry : crucigrama.getDefiniciones().entrySet()) {
                    try {
                        entry.setValue(Scrap.getWord(entry.getKey(), Scrap.DICT.GOOGLE));
                        progress++;
                        setProgress((progress * 100) / cant);
                    } catch (IOException e) {
                        System.out.println("DURANTE GOOGLE SCRAP: " + e);
                    }
                }
                return null;
            }
            @Override
            public void done() {
                Toolkit.getDefaultToolkit().beep();
                setCursor(null); //turn off the wait cursor
            }
        };
        sw.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if ("progress".equals(evt.getPropertyName())) {
                int progress = (Integer) evt.getNewValue();
                System.out.println("PROGRESS: " + evt.getNewValue());
                jProgressBar1.setValue(progress);
            }
        });
        sw.execute();
    }

    private void cargarDefiniciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDefiniciones
        cargarDefs();
    }//GEN-LAST:event_cargarDefiniciones

    private void horizontItemList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_horizontItemList1ValueChanged
        verticalItemList.clearSelection();
        int index = horizontItemList1.getSelectedIndex();
        if (index >= 0) {
            String selectedWord = crucigrama.getHorizPairsList().get(index).second;
            palabraSeleccionada.setText(selectedWord);
            definitionTextPane.setText(crucigrama.getDefiniciones().get(selectedWord));
        }
    }//GEN-LAST:event_horizontItemList1ValueChanged

    private void verticalItemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_verticalItemListValueChanged
        horizontItemList1.clearSelection();
        int index = verticalItemList.getSelectedIndex();
        if (index >= 0) {
            String selectedWord = crucigrama.getVertiPairList().get(index).second;
            palabraSeleccionada.setText(selectedWord);
            definitionTextPane.setText(crucigrama.getDefiniciones().get(selectedWord));
        }
    }//GEN-LAST:event_verticalItemListValueChanged


    private void modificarDef(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarDef
        crucigrama.getDefiniciones().replace(palabraSeleccionada.getText(), definitionTextPane.getText());
        statusJLabel.setText(palabraSeleccionada.getText() + " was saved locally...");
        // CompletableFuture<String> completableFuture = CompletableFuture.supplyAsync(() -> "Supply Async...");
        scheduleResetStatus();

    }//GEN-LAST:event_modificarDef

    private void updateDB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDB
        if (saveAllSQL) {
            statusJLabel.setText("Saving all new defs to DB");
            try {

                JdbcConnection.updateAll(crucigrama.getDefiniciones());
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println("EXCEPTION: " + e);
                statusJLabel.setText("Ocurrió un error al tratar de guardar defs");
            }
            statusJLabel.setText("All defs saved successfully");

        } else {
            statusJLabel.setText("Saving new def to DB");
            try {
                JdbcConnection.update(palabraSeleccionada.getText(), definitionTextPane.getText());
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println("EXCEPTION: " + e);
                statusJLabel.setText("Ocurrió un error al tratar de guarda la def");
            }
            statusJLabel.setText("Def saved successfully");
        }
        scheduleResetStatus();
    }//GEN-LAST:event_updateDB

    private void cargadDefsFromDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargadDefsFromDBActionPerformed
        try {
            JdbcConnection.executeMultipleRead(crucigrama.getDefiniciones());
        } catch (Exception e) {
            System.out.println("EXCEPTION: " + e);
        }
    }//GEN-LAST:event_cargadDefsFromDBActionPerformed

    private void scrapWord(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrapWord
        String cadena = "";
        try {
            cadena = Scrap.getWord(palabraSeleccionada.getText(), Scrap.DICT.GOOGLE);
        } catch (IOException ex) {
            Logger.getLogger(Definitions.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        definitionTextPane.setText(cadena);

    }//GEN-LAST:event_scrapWord

    private void saveToIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToIDButtonActionPerformed
        IDExporter idExporter = new IDExporter(12, 10);
        idExporter.addTitle("HORIZONTALES");
        for (Pair<Integer, String> pair : crucigrama.getHorizPairsList()) {
            String def = crucigrama.getDefiniciones().get(pair.second.split("\n")[0]);
            idExporter.addItem(String.valueOf(pair.first), def);
        }
        idExporter.addTitle("VERTICALES");
        for (Pair<Integer, String> pair : crucigrama.getVertiPairList()) {
            String def = crucigrama.getDefiniciones().get(pair.second.split("\n")[0]);
            idExporter.addItem(String.valueOf(pair.first), def);
        }
        try {
            idExporter.saveToFile();
        } catch (IOException ex) {
            Logger.getLogger(Definitions.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveToIDButtonActionPerformed

    private void saveAllCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saveAllCheckBoxItemStateChanged
        System.out.println("CHECKBOX");
        saveAllSQL = saveAllCheckBox.isSelected() ? true : false; // Por las dudas evito hacer cosas como *=-1 o el operador ^=
        System.out.println("SAVE ALL STATE? : " + saveAllSQL);
    }//GEN-LAST:event_saveAllCheckBoxItemStateChanged

    public void latentEditing() {
        Timer tm = new Timer();
        TimerTask tt = new TimerTask() {
            int green = 125;
            int step = +1;

            @Override
            public void run() {
                green += step;
                if (green >= 255 || green <= 1) {
                    step *= -1;
                }
                System.out.println("green: " + green);
                editModeToggle.setBackground(new Color(125, green, 125));
            }
        };
        tm.schedule(tt, 0, 120);
    }
    private void editModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editModeToggleActionPerformed
        editing ^= editing;
        if (editModeToggle.isSelected()) {
            System.out.println("EDITING");
            cargadDefsFromDB.setEnabled(false);
            cargarDefBtn.setEnabled(false);
            updateDB.setEnabled(false);
            saveAllCheckBox.setEnabled(false);

        } else {
            System.out.println("UNLOCKED");
            cargadDefsFromDB.setEnabled(true);
            cargarDefBtn.setEnabled(true);
            updateDB.setEnabled(true);
            saveAllCheckBox.setEnabled(true);
            // latentEditing();
        }

    }//GEN-LAST:event_editModeToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Definitions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Definitions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Definitions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Definitions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Definitions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargadDefsFromDB;
    private javax.swing.JButton cargarDefBtn;
    private javax.swing.JTextPane definitionTextPane;
    private javax.swing.JToggleButton editModeToggle;
    private javax.swing.JList<String> horizontItemList1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel palabraSeleccionada;
    private javax.swing.JCheckBox saveAllCheckBox;
    private javax.swing.JButton saveToIDButton;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JButton updateDB;
    private javax.swing.JList<String> verticalItemList;
    // End of variables declaration//GEN-END:variables
}
