/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.Pair;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Stroke;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.geom.GeneralPath;
import java.awt.image.AffineTransformOp;
import static java.awt.image.AffineTransformOp.TYPE_BICUBIC;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;

import javax.swing.text.Element;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;

import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import com.jml.gorigrama.GorigramaEntity;
import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import javax.imageio.ImageIO;
import org.apache.fontbox.util.autodetect.FontFileFinder;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author jmlucero
 */
public class TextWrapper extends javax.swing.JFrame {

    /**
     * Creates new form TextWrapper
     */
    //jTextPane.setEditorKit(new HTMLEditorKit());
    private GorigramaEntity gorigrama;
    String definiciones = "";

    javax.swing.text.Document doc;
    SimpleAttributeSet normal;
    BufferedImage bfToPrint;
    ImagePanel imp = new ImagePanel();

    public TextWrapper() {
        initComponents();

        doc = this.jTextPane2.getDocument();

    }

    public TextWrapper(BufferedImage bf, GorigramaEntity gorigrama) {
        this();
        this.bfToPrint = bf;
        this.gorigrama = gorigrama;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new ImagePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        saveToPDFButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        loadButton.setText("LOAD");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        printButton.setText("PRINT");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setDoubleBuffered(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextPane2.setBackground(new java.awt.Color(153, 255, 204));
        jTextPane2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextPane2.setPreferredSize(new java.awt.Dimension(595, 300));
        jScrollPane1.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane1);

        saveToPDFButton.setText("SAVE TO PDF");
        saveToPDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToPdf(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(loadButton)
                .addGap(40, 40, 40)
                .addComponent(saveToPDFButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(printButton)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(printButton)
                    .addComponent(saveToPDFButton))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private BufferedImage resizeImage(BufferedImage originalImage, int targetWidth, int targetHeight) throws IOException {
        BufferedImage resizedImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = resizedImage.createGraphics();
        graphics2D.drawImage(originalImage, 0, 0, targetWidth, targetHeight, null);
        graphics2D.dispose();
        return resizedImage;
    }

    private BufferedImage scaleAffine(BufferedImage originalImage, int targetWidth, int targetHeight) throws IOException {
        AffineTransform tx = AffineTransform.getScaleInstance(0.5, 0.5);
        tx.translate(0, 30);
        BufferedImageOp bdop = new AffineTransformOp(tx, TYPE_BICUBIC);
        BufferedImage resizedImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = resizedImage.createGraphics();
        graphics2D.drawImage(originalImage, bdop, 0, 0);
        graphics2D.dispose();

        return resizedImage;
    }
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
       definiciones = "";
        try {
            //Image image = Toolkit.getDefaultToolkit().getImage("C:\\Users\\jmluc\\Desktop\\cruci__.jpg");
            //  ImageIcon icon = new ImageIcon(image);
            //    jTextPane1.insertIcon(icon);
            int targetWidth = gorigrama.getNumCeldasH()*16;
            int targetHeight=gorigrama.getNumCeldasV()*16;

            ImageIcon icon = new ImageIcon(scaleAffine(bfToPrint, targetWidth, targetHeight));
            //jTextPane3.insertIcon(icon);
            // gr.drawImage(bfToPrint, 0   , 0, null);

            /*AffineTransform tx = AffineTransform.getScaleInstance(0.5, 0.5);
            tx.translate(0, 30);
            BufferedImageOp  bdop = new AffineTransformOp(tx, TYPE_BICUBIC);
            Graphics2D gr = (Graphics2D) bfToPrint.getGraphics();
            gr.drawImage(bfToPrint, bdop, 0, 0);
            gr.dispose();*/
             ((ImagePanel) jPanel2).setImage(resizeImage(bfToPrint, targetWidth, targetHeight)); 
            normal = new SimpleAttributeSet();
            StyleConstants.setAlignment(normal, StyleConstants.ALIGN_JUSTIFIED);
            StyleConstants.setForeground(normal, Color.BLACK);
            StyledDocument documentStyle = jTextPane2.getStyledDocument();

            documentStyle.setParagraphAttributes(0, documentStyle.getLength(), normal, false);
            definiciones+="HORIZONTALES\n ";
            for (Pair<Integer, String> pair : gorigrama.getHorizPairsList()) {
                String def = gorigrama.getDefiniciones().get(pair.second).split("\n")[0]; //Supposed to have multiple defs
                definiciones+=String.valueOf(pair.first)+"."+def+". ";
            }
            definiciones+="\nVERTICALES\n ";
            for (Pair<Integer, String> pair : gorigrama.getVertiPairList()) {
                String def = gorigrama.getDefiniciones().get(pair.second).split("\n")[0];
                 definiciones+=String.valueOf(pair.first)+"."+def+". ";
            }
            doc.insertString(doc.getLength(), definiciones, normal);

            jTextPane2.setDocument(doc);
            jTextPane2.setSize(500, 1000);
            
     

        } catch (BadLocationException ex) {
            Logger.getLogger(TextWrapper.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TextWrapper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        MessageFormat headerFormat = new MessageFormat("dsfsdf");
        MessageFormat footerFormat = new MessageFormat("sdfsdfsf");
        PrintService service = PrintServiceLookup.lookupDefaultPrintService();
        PrintRequestAttributeSet attributes = new HashPrintRequestAttributeSet();
        attributes.add(OrientationRequested.PORTRAIT);

        attributes.add(new JobName("My job", null));

        PrinterJob pj = PrinterJob.getPrinterJob();
        Printable pt = new Printable() {
            @Override
            public int print(Graphics g, PageFormat pf, int page) throws PrinterException {
                if (page > 0) {
                    /* We have only one page, and 'page' is zero-based */
                    return NO_SUCH_PAGE;
                }

                /* User (0,0) is typically outside the imageable area, so we must
         * translate by the X and Y values in the PageFormat to avoid clipping
                 */
                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                /* Now print the window and its visible contents */
                jPanel1.printAll(g);

                /* tell the caller that this page is part of the printed document */
                return PAGE_EXISTS;
            }
        };

        pj.setPrintable(pt);

        /* locate a print service that can handle the request */
        PrintService[] services = PrinterJob.lookupPrintServices();

        System.out.println("selected printer " + services[2].getName());
        try {
            pj.setPrintService(services[2]);
            pj.pageDialog(attributes);
            if (pj.printDialog(attributes)) {
                pj.print(attributes);
            }
        } catch (PrinterException pe) {
            System.err.println(pe);
        }
    }//GEN-LAST:event_printButtonActionPerformed
public byte[] convertImageToByteArray(BufferedImage image, String format) {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

    try {
        // Write the BufferedImage to the ByteArrayOutputStream in the specified format
        ImageIO.write(image, format, byteArrayOutputStream);
    } catch (IOException e) {
        e.printStackTrace();
    }

    // Get the byte array from the ByteArrayOutputStream
    return byteArrayOutputStream.toByteArray();
}
    private void saveToPdf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToPdf
        com.itextpdf.text.Document pdfDoc = new com.itextpdf.text.Document(PageSize.A4);
        try {
            PdfWriter.getInstance(pdfDoc, new FileOutputStream("C:\\Users\\jmluc\\Desktop\\c.pdf"))
                    .setPdfVersion(PdfWriter.PDF_VERSION_1_7);
            pdfDoc.open();
    

            com.itextpdf.text.Font myfo;
             
             FontFactory.register("src\\main\\resources\\fonts\\JetBrainsMono-Medium.ttf", "JetBrains");
              FontFactory.registerDirectory("src\\main\\resources\\fonts");
               myfo = FontFactory.getFont("jetbrains", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
             System.out.println("REGISTERED FONTS");
             System.out.println(FontFactory.getRegisteredFonts());
               System.out.println("REGISTERED FAMILIES");
             System.out.println(FontFactory.getRegisteredFamilies());
        
       
   
           
        
            //myfo.setStyle(com.itextpdf.text.Font.NORMAL);
            myfo.setSize(10);
            pdfDoc.add(new Paragraph("\n"));
            com.itextpdf.text.Image img = new com.itextpdf.text.Jpeg(convertImageToByteArray(bfToPrint,"JPG"));
            img.setDpi(150, 150);
            img.scaleToFit(550, 500);
            pdfDoc.add(img);
            pdfDoc.add(new Paragraph("\n"));
 
            
            
            
            //BufferedReader br = new BufferedReader(new FileReader(filename));
            //String strLine;
            /*while ((strLine = br.readLine()) != null) {
			Paragraph para = new Paragraph(strLine + "\n", myfont);
			para.setAlignment(Element.ALIGN_JUSTIFIED);
			pdfDoc.add(para);
            }*/
            Paragraph para = new Paragraph(definiciones, myfo);
            para.setAlignment(com.itextpdf.text.Element.ALIGN_JUSTIFIED);
            pdfDoc.add(para);

            pdfDoc.close();
        } catch (Exception ex) {
            Logger.getLogger(TextWrapper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveToPdf

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextWrapper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveToPDFButton;
    // End of variables declaration//GEN-END:variables

}
