/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Stroke;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashAttributeSet;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author jmlucero
 */
public class TextWrapper extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form TextWrapper
     */
    //jTextPane.setEditorKit(new HTMLEditorKit());
    String desiderata = "Camina plácido entre el ruido y la prisa, y recuerda la paz que se puede encontrar en el silencio."
            + " En cuanto te sea posible y sin rendirte, mantén buenas relaciones con todas las personas. "
            + "Enuncia tu verdad de una manera serena y clara, y escucha a los demás, incluso al torpe e ignorante,"
            + " también ellos tienen su propia historia. Evita a las personas ruidosas y agresivas,"
            + " ya que son un fastidio para el espíritu. Si te comparas con los demás, te volverás vano"
            + " o amargado pues siempre habrá personas más grandes y más pequeñas que tú. Disfruta de tus éxitos,"
            + " lo mismo que de tus planes. Mantén el interés en tu propia carrera, por humilde que sea, ella es un "
            + "verdadero tesoro en el fortuito cambiar de los tiempos. Sé cauto en tus negocios, pues el mundo está lleno"
            + " de engaños. Pero no dejes que esto te vuelva ciego para la virtud que existe, hay muchas personas que se"
            + " esfuerzan por alcanzar nobles ideales, la vida está llena de heroísmo. Sé tú mismo, y en especial no"
            + " finjas el afecto, y no seas cínico acerca del amor, pues en medio de todas las arideces y desengaños,"
            + " es perenne como la hierba. Toma amablemente el consejo de los años, abandonando con donaire las cosas"
            + " de la juventud. Cultiva la firmeza del espíritu para que te proteja de las adversidades repentinas, "
            + "mas no te agotes con pensamientos oscuros, muchos temores nacen de la fatiga y la soledad. Más allá de"
            + " una sana disciplina, sé benigno contigo mismo. Tú eres una criatura del universo, no menos que los árboles"
            + " y las estrellas, tienes derecho a existir, y sea que te resulte claro o no, indudablemente el universo "
            + "marcha como debiera. Por eso debes estar en paz con Dios, cualquiera que sea tu idea de Él, y sean cualesquiera"
            + " tus trabajos y aspiraciones, conserva la paz con tu alma en la bulliciosa confusión de la vida."
            + " Aún con todas sus farsas, penalidades y sueños fallidos, el mundo es todavía hermoso. Sé alegre. "
            + "Esfuérzate por ser feliz";

    Document doc;
    SimpleAttributeSet normal;
    BufferedImage bfToPrint;

    public TextWrapper() {
        initComponents();

        doc = this.jTextPane1.getDocument();

    }
    
    public TextWrapper(BufferedImage bf){
        this();
        this.bfToPrint = bf;
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jEditorPane1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.setDoubleBuffered(true);
        jTextPane1.setStyledDocument(jTextPane1.getStyledDocument());
        jScrollPane2.setViewportView(jTextPane1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jButton2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jEditorPane1.setText(desiderata);

        try {
             //Image image = Toolkit.getDefaultToolkit().getImage("C:\\Users\\jmluc\\Desktop\\cruci__.jpg");
      //  ImageIcon icon = new ImageIcon(image);
        //    jTextPane1.insertIcon(icon);
       
       ImageIcon icon = new ImageIcon(bfToPrint);
  
        // gr.drawImage(bfToPrint, 0   , 0, null);
          
                jTextPane1.insertIcon(icon);
        
            normal = new SimpleAttributeSet();
            StyleConstants.setAlignment(normal, StyleConstants.ALIGN_JUSTIFIED);
            StyleConstants.setForeground(normal, Color.red);
            StyledDocument documentStyle = jTextPane1.getStyledDocument();
            documentStyle.setParagraphAttributes(0, documentStyle.getLength(), normal, false);
            doc.insertString(doc.getLength(), desiderata, normal);

            this.jTextPane1.setDocument(doc);
        } catch (BadLocationException ex) {
            Logger.getLogger(TextWrapper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat headerFormat = new MessageFormat("dsfsdf");
        MessageFormat footerFormat = new MessageFormat("sdfsdfsf");
        PrintService service = PrintServiceLookup.lookupDefaultPrintService();
        PrintRequestAttributeSet attributes = new HashPrintRequestAttributeSet();
        attributes.add(OrientationRequested.PORTRAIT);

        try {
            jTextPane1.print(headerFormat, footerFormat, true, service, attributes, true);

            /*PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable((Printable) this);
            boolean ok = job.printDialog();
            if (ok) {
            try {
            job.print();
            } catch (PrinterException ex) {
            
            }
            } */
        } catch (PrinterException ex) {
            Logger.getLogger(TextWrapper.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextWrapper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics grphcs, PageFormat pf, int page) throws PrinterException {
        if (page > 0) {
            /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }

        /* User (0,0) is typically outside the imageable area, so we must
         * translate by the X and Y values in the PageFormat to avoid clipping
         */
        Graphics2D g2d = (Graphics2D) jTextPane1.getGraphics();
        g2d.translate(pf.getImageableX(), pf.getImageableY());

        /* tell the caller that this page is part of the printed document */
        return PAGE_EXISTS;
    }
}
